### ISSUE TITLE
VMs fail when deploying in HA

### ISSUE THREAD

**Issue by huzer1** [F5Networks/terraform-azure-bigip-module#64]
When deploying, the VM fails it's ready check if deploying multiple times to the same location. 
`mgmt state UP mode DEFAULT qlen 1000\    link/ether 00:22:48:bf:8a:ff brd ff:ff:ff:ff:ff:ff" }]
2024-03-20T20:37:31.491513Z INFO Daemon Daemon Agent WALinuxAgent-2.2.48.1 launched with command 'python -u /usr/sbin/waagent -run-exthandlers' is successfully running
2024-03-20T20:52:34.940949Z INFO ExtHandler ExtHandler [HEARTBEAT] Agent WALinuxAgent-2.2.48.1 is running as the goal state agent
2024-03-20T21:22:37.504979Z INFO ExtHandler ExtHandler [HEARTBEAT] Agent WALinuxAgent-2.2.48.1 is running as the goal state agent
2024-03-20T21:52:39.921984Z INFO ExtHandler ExtHandler [HEARTBEAT] Agent WALinuxAgent-2.2.48.1 is running as the goal state agent
2024-03-20T22:22:42.608616Z INFO ExtHandler ExtHandler [HEARTBEAT] Agent WALinuxAgent-2.2.48.1 is running as the goal state agent
2024-03-20T22:52:45.109139Z INFO ExtHandler ExtHandler [HEARTBEAT] Agent WALinuxAgent-2.2.48.1 is running as the goal state agent
2024-03-20T23:22:45.465325Z INFO ExtHandler ExtHandler [HEARTBEAT] Agent WALinuxAgent-2.2.48.1 is running as the goal state agent
2024-03-20T23:52:46.030279Z INFO ExtHandler ExtHandler [HEARTBEAT] Agent WALinuxAgent-2.2.48.1 is running as the goal state agent
2024-03-21T00:22:48.542516Z INFO ExtHandler ExtHandler [HEARTBEAT] Agent WALinuxAgent-2.2.48.1 is running as the goal state agent
[15103.570400] mlx4_core 0005:00:02.0: going promisc on 1
[15104.560700] mlx4_core 0004:00:02.0: going promisc on 1
[15105.438951] mlx4_core 0002:00:02.0: going promisc on 1
[15106.534804] mlx4_core 0003:00:02.0: going promisc on 1
2024-03-21T00:35:36.680414Z WARNING MonitorHandler ExtHandler An error occurred in the monitor thread main loop; will skip the current iteration.
[ProtocolError] Exceeded max retry updating goal state
2024-03-21T00:35:36.684918Z WARNING ExtHandler ExtHandler An error occurred while retrieving the goal state: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/azurelinuxagent/common/protocol/wire.py", line 713, in try_update_goal_state
    self.update_goal_state()
  File "/usr/lib/python2.7/site-packages/azurelinuxagent/common/protocol/wire.py", line 706, in update_goal_state
    WireClient._UpdateType.GoalStateForced if forced else WireClient._UpdateType.GoalState)
  File "/usr/lib/python2.7/site-packages/azurelinuxagent/common/protocol/wire.py", line 769, in _update_from_goal_state
    raise ProtocolError("Exceeded max retry updating goal state")
ProtocolError: [ProtocolError] Exceeded max retry updating goal state

2024-03-21T00:35:36.704746Z WARNING ExtHandler ExtHandler [PERIODIC] Attempts to retrieve the goal state are failing: [ProtocolError] Exceeded max retry updating goal state
2024-03-21T00:38:44.840569Z WARNING MonitorHandler ExtHandler An error occurred in the monitor thread main loop; will skip the current iteration.
[ProtocolError] Exceeded max retry updating goal state
2024-03-21T00:41:49.016347Z WARNING MonitorHandler ExtHandler An error occurred in the monitor thread main loop; will skip the current iteration.
[ProtocolError] Exceeded max retry updating goal state`

If I change the availability zone or wait an extended period of time (over 8 hours) the exact same deployment will succeed.

**Comment by pgouband** [comment]
Hi @huzer1,

Are you following one of the examples?
https://github.com/F5Networks/terraform-azure-bigip-module/tree/main/examples

**Comment by shipszky** [comment]
Yes, the 4-Nic in particular. I've also experienced this outside of this template, creating deployments from scratch.

**Comment by shipszky** [comment]
This was my error. I had broken the random ID.
